### ISSUE TITLE
Include

### ISSUE THREAD

**Issue by Keats** [Keats/scl#1]
It was in the my original spec but removed but simplicity for first version.

## Includes
A SCL file can include another SCL file in two ways:

- without a key
- with a key

Includes can only happen at the root level or in a dictionary.

```toml
# without a key
include "ssl.scl"

# with a key
ssl = include "ssl.scl"

# in a dict
site = {
    ssl = include "ssl.scl"
}

# INVALID
ips = [include "ssl.scl"]
```

If there is no key, the data from the included file will be directly in the current level: the root or the dict the include is in.
